#!/system/bin/sh

IN_START="@IN_START@"

STARTER_PATH="@STARTER_PATH@"
APP_PATH="@APP_PATH@"
SERVER_NAME="@SERVER_NAME@"
CLASS_NAME="@CLASS_NAME@"

cp -f $IN_START $STARTER_PATH

chmod 700 $STARTER_PATH
chown 2000 $STARTER_PATH
chgrp 2000 $STARTER_PATH

echo "run start ..."
if $STARTER_PATH $APP_PATH $SERVER_NAME $CLASS_NAME; then
  echo "Success"
fi