#!/system/bin/sh

IN_START="@IN_START@"
OUT_START="@OUT_START@"

IN_LIB="@IN_LIB@"
OUT_LIB="@OUT_LIB@"

APP_PATH="@APP_PATH@"
SERVER_NAME="@SERVER_NAME@"
CLASS_NAME="@CLASS_NAME@"

cp -f $IN_START $OUT_START
cp -f $IN_LIB $OUT_LIB

chmod 700 $OUT_START
chown 2000 $OUT_START
chgrp 2000 $OUT_START

echo "run starter ..."
if $OUT_START $APP_PATH $SERVER_NAME $CLASS_NAME; then
  echo "Success"
fi